#!/usr/bin/env bash
# Carries the groundcover patch stack onto an upstream Grafana tag.
#
#   .groundcover/carry.sh <tag>           pick the stack onto <tag> as branch gc/<tag>, then finish
#   .groundcover/carry.sh --finish <tag>  after resolving a stopped pick and `git cherry-pick --continue`
#
# The stack is every commit from the recorded base (.groundcover/upstream) to HEAD, except the last
# "gc(carry):" commit, which finish always regenerates: upstream workflow removal, generated
# feature toggles, go.mod/go.sum from deps.txt. Commits with an Upstream-Commit trailer are dropped
# once the target tag contains that commit.
set -euo pipefail

if [ -z "${CARRY_REEXEC:-}" ]; then # the stack checkout replaces this file mid-run
	tmp=$(mktemp)
	cp "$0" "$tmp"
	CARRY_REEXEC=1 exec bash "$tmp" "$@"
fi
cd "$(git rev-parse --show-toplevel)"

UPSTREAM_URL=${UPSTREAM_URL:-https://github.com/grafana/grafana.git}
GC_WORKFLOWS='^\.github/workflows/(pr|release|carry-upstream)\.yaml$'
git config rerere.enabled true

die() {
	echo "carry: $*" >&2
	exit 1
}

# version_lt a b: a sorts before b (v prefix ignored)
version_lt() {
	[ "$1" != "$2" ] && [ "$(printf '%s\n%s\n' "${1#v}" "${2#v}" | sort -V | head -1)" = "${1#v}" ]
}

picking() { git rev-parse -q --verify CHERRY_PICK_HEAD >/dev/null; }

# Resolves conflicts that have a mechanical answer; returns 1 if any remain.
autoresolve() {
	local f left=0
	for f in $(git diff --name-only --diff-filter=U); do
		if [[ $f == .github/* && ! $f =~ $GC_WORKFLOWS ]]; then
			git rm -q -f "$f"
		elif [[ $f == pkg/services/featuremgmt/toggles_gen* ]]; then
			git checkout -q --ours -- "$f" && git add "$f" # regenerated by finish
		else
			left=1
		fi
	done
	return $left
}

stop() {
	echo "## carry stopped on $(git log -1 --format='%h %s' CHERRY_PICK_HEAD)"
	echo "Conflicts:"
	git diff --name-only --diff-filter=U | sed 's/^/- /'
	echo "Remaining picks:"
	sed -n 's/^pick /- /p' "$(git rev-parse --git-path sequencer/todo)" 2>/dev/null || true
	echo "Resolve, git add, git cherry-pick --continue, then: .groundcover/carry.sh --finish $1"
	exit 2
}

pick() {
	local tag=$1 base c up last picks=()
	base=$(cat .groundcover/upstream)
	[ -z "$(git status --porcelain --untracked-files=no)" ] || die "working tree not clean"
	for c in "$base" "$tag"; do
		git rev-parse -q --verify "refs/tags/$c" >/dev/null || git fetch -q --no-tags "$UPSTREAM_URL" "+refs/tags/$c:refs/tags/$c"
	done

	last=$(git rev-parse HEAD)
	[[ $(git log -1 --format=%s HEAD) == gc\(carry\):* ]] || last=
	for c in $(git rev-list --reverse --no-merges "$base..HEAD"); do
		[ "$c" = "$last" ] && continue
		up=$(git log -1 --format='%(trailers:key=Upstream-Commit,valueonly)' "$c" | head -1)
		if [ -n "$up" ] && git merge-base --is-ancestor "$up" "$tag" 2>/dev/null; then
			echo "drop $(git log -1 --format='%h %s' "$c") (in $tag)"
			continue
		fi
		picks+=("$c")
	done

	git checkout -q -B "gc/$tag" "$tag^{commit}"
	git cherry-pick --allow-empty "${picks[@]}" || true
	while picking; do
		autoresolve || stop "$tag"
		if git diff --cached --quiet; then
			git cherry-pick --skip || true
		else
			git -c core.editor=true cherry-pick --continue || true
		fi
	done
	finish "$tag"
}

apply_deps() {
	local dirs d a b c cur alerting
	dirs=$(go work edit -json | jq -r '.Use[].DiskPath')
	alerting=$(go mod edit -json | jq -r '.Require[] | select(.Path == "github.com/grafana/alerting") | .Version')
	grep -q "^alerting $alerting " .groundcover/deps.txt ||
		die "no groundcover-com/alerting version mapped in deps.txt for grafana/alerting $alerting"
	while read -r a b c; do
		case $a in
		'' | '#'*) ;;
		go)
			for d in $dirs; do
				cur=$(go mod edit -json "$d/go.mod" | jq -r .Go)
				if version_lt "$cur" "$b"; then go mod edit -go="$b" "$d/go.mod"; fi
			done
			if version_lt "$(go work edit -json | jq -r .Go)" "$b"; then go work edit -go="$b"; fi
			;;
		alerting)
			if [ "$b" = "$alerting" ]; then
				go mod edit -replace="github.com/grafana/alerting=github.com/groundcover-com/alerting@$c"
				go work edit -replace="github.com/grafana/alerting=github.com/groundcover-com/alerting@$c"
			fi
			;;
		*)
			for d in $dirs; do
				cur=$(go mod edit -json "$d/go.mod" | jq -r --arg m "$a" '.Require[]? | select(.Path == $m) | .Version')
				if [ -n "$cur" ] && version_lt "$cur" "$b"; then go mod edit -require="$a@$b" "$d/go.mod"; fi
			done
			;;
		esac
	done <.groundcover/deps.txt
}

tidy() {
	local d
	for d in $(go work edit -json | jq -r '.Use[].DiskPath'); do
		# submodules may import workspace-only packages; upstream's update-workspace.sh tolerates that too
		if [ "$d" = . ]; then go mod tidy; else (cd "$d" && go mod tidy) || true; fi
	done
	go work sync
}

finish() {
	local tag=$1
	! picking || die "cherry-pick in progress"
	git ls-files .github/workflows .github/ISSUE_TEMPLATE | { grep -Ev "$GC_WORKFLOWS" || true; } | xargs -r git rm -q
	apply_deps
	tidy
	apply_deps # modules first required by tidy (groundcover code imports)
	tidy
	go test ./pkg/services/featuremgmt/ >/dev/null 2>&1 || go test ./pkg/services/featuremgmt/ >/dev/null ||
		die "feature toggle generation failed"
	echo "$tag" >.groundcover/upstream
	git add -A
	git commit -q -m "gc(carry): $tag base, regenerated deps and generated files"

	make gen-go
	go build ./pkg/...
	go test -count=1 ./pkg/services/ngalert/state/... ./pkg/services/ngalert/sender/... \
		./pkg/services/ngalert/schedule/... ./pkg/services/ngalert/remote/... ./pkg/services/featuremgmt/...
	go test -count=1 -run 'TestGC' ./pkg/api/
	echo "carry: gc/$tag ready ($(git rev-list --count "$tag..HEAD") commits on $tag)"
}

case ${1:-} in
--finish) finish "${2:?tag}" ;;
v*) pick "$1" ;;
*) die "usage: carry.sh <tag> | --finish <tag>" ;;
esac
